// Generated by CoffeeScript 2.5.1
(function() {
  var PORT, app, express, http, io, mineflayer, server, socketInfo;

  express = require('express');

  app = express();

  http = require("http");

  server = http.createServer(app);

  io = require("socket.io")(server, {
    cors: {
      origin: "*"
    }
  });

  mineflayer = require("mineflayer");

  socketInfo = {};

  PORT = 8081;

  server.listen(PORT, function() {
    return console.log(`Server is running on \x1b[34m*:${PORT}\x1b[0m`);
  });

  io.sockets.on("connection", function(socket) {
    socketInfo[socket.id] = {};
    socket.on("initClient", function(nick) {
      console.log(`[\x1b[32m+\x1b[0m] ${nick}`);
      socketInfo[socket.id].nick = nick;
      socketInfo[socket.id].bot = mineflayer.createBot({
        host: "localhost",
        port: 25565,
        username: nick
      });
    });
    socket.on("disconnect", function() {
      console.log(`[\x1b[31m-\x1b[0m] ${socketInfo[socket.id].nick}`);
      socketInfo[socket.id].bot.end();
      delete socketInfo[socket.id];
    });
  });

}).call(this);
